<h1>Category List</h1>

<table class="table">
	<thead>
		<tr>
			<th>Id</th>
			<th>Name</th>
			<th>Position</th>
			<th>Action</th>
		</tr>
	</thead>
	
	<tbody>
		<?php foreach ($this->categories as $category):?>
			<tr>
				<td><?php echo ($category->getId())?></td>
				<td><?php echo ($category->getName())?></td>
				<td><?php echo ($category->getPostion())?></td>
				<td>
			</tr>
		<?php endforeach;?>
	</tbody>
</table>
