<h1>Edit Post</h1>
<form method="post" action="">
	<div class="form-group">
	    <label>Title</label>
	    <input name="title" value="<?php echo $this->blog->getTitle()?>" type="text" class="form-control" placeholder="Enter the blog title">
	</div>
	<div class="form-group">
	    <label >Content</label>
	   	<textarea name="content" rows="" cols="" class="form-control"><?php echo $this->blog->getContent()?></textarea>
	</div>
	
	<div class="form-group">
	    <label>Author</label>
	    <input name="author"  value="<?php echo $this->blog->getAuthor()?>" type="text" class="form-control" placeholder="Enter author's name">
	</div>
	
	<button type="submit" class="btn btn-default">Submit</button>

</form>